(function() {var implementors = {};
implementors["backtrace"] = [{text:"impl !<a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Sync.html\" title=\"trait core::marker::Sync\">Sync</a> for <a class=\"struct\" href=\"backtrace/struct.Frame.html\" title=\"struct backtrace::Frame\">Frame</a>",synthetic:true,types:["backtrace::backtrace::Frame"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Sync.html\" title=\"trait core::marker::Sync\">Sync</a> for <a class=\"struct\" href=\"backtrace/struct.Symbol.html\" title=\"struct backtrace::Symbol\">Symbol</a>",synthetic:true,types:["backtrace::symbolize::Symbol"]},{text:"impl&lt;'a&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Sync.html\" title=\"trait core::marker::Sync\">Sync</a> for <a class=\"struct\" href=\"backtrace/struct.SymbolName.html\" title=\"struct backtrace::SymbolName\">SymbolName</a>&lt;'a&gt;",synthetic:true,types:["backtrace::symbolize::SymbolName"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Sync.html\" title=\"trait core::marker::Sync\">Sync</a> for <a class=\"struct\" href=\"backtrace/struct.Backtrace.html\" title=\"struct backtrace::Backtrace\">Backtrace</a>",synthetic:true,types:["backtrace::capture::Backtrace"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Sync.html\" title=\"trait core::marker::Sync\">Sync</a> for <a class=\"struct\" href=\"backtrace/struct.BacktraceFrame.html\" title=\"struct backtrace::BacktraceFrame\">BacktraceFrame</a>",synthetic:true,types:["backtrace::capture::BacktraceFrame"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Sync.html\" title=\"trait core::marker::Sync\">Sync</a> for <a class=\"struct\" href=\"backtrace/struct.BacktraceSymbol.html\" title=\"struct backtrace::BacktraceSymbol\">BacktraceSymbol</a>",synthetic:true,types:["backtrace::capture::BacktraceSymbol"]},{text:"impl&lt;'a&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Sync.html\" title=\"trait core::marker::Sync\">Sync</a> for <a class=\"enum\" href=\"backtrace/enum.BytesOrWideString.html\" title=\"enum backtrace::BytesOrWideString\">BytesOrWideString</a>&lt;'a&gt;",synthetic:true,types:["backtrace::types::BytesOrWideString"]},];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
